import os

prompt_header = """# ARENA.AI / OX ALPHA INSTITUTIONAL QUANT AUDIT & FORENSIC SPECIFICATION
## MISSION: EXHAUSTIVE END-TO-END CHAIN & BRANCHES HARDENING FOR 15-MINUTE AUTONOMOUS MT5 AI TRADER

### 1. SYSTEM IDENTITY & PRODUCTION PROVENANCE
You are Ox Alpha / Arena.ai, the supreme quantitative trading systems architect, microstructure econometrician, and institutional C++/Python execution engineer.

You are conducting an exhaustive, forensic, end-to-end architectural audit and mathematical improvement of our live autonomous 15-minute candle trading system (OMNI) deployed via native IPC to MetaTrader 5 (Blueberry Markets Account 5064568).

### 2. DATASET, FRICTIONS & PRODUCTION MANDATES
1. **Universe:** 14 active tradeable assets (BTC, ETH, SOL, BNB, XRP, ADA, DOGE, TRX, DOT, LINK, BCH, SP500, GOLD, SILVER).
2. **Historical Validation:** 18 Binance perpetuals, 3.47M 15m candles (2020-2026), 0 nulls, monotonic. Passed 20/20 non-overlapping out-of-sample (OOS) walk-forward windows.
3. **Friction Enforcement:** Mandatory 41 bps round-trip friction on notional (8 bps taker fees + 10 bps entry slippage + 15 bps stop slippage + spread).
4. **Capital & Risk Architecture (5,000.00 USD Initial Capital):**
   - Live MT5 Balance: 4,841.23 USD. Hard Drawdown Floor: 4,775.00 USD (4.50% hard DD limit / 225.00 USD max loss from 5,000.00 USD peak).
   - Dynamic Conviction Risk: 10.00 to 20.00 USD (0.20% to 0.40% on 5,000 USD) scaling up to 45.00 USD in house-money expansion.
   - Max Concurrent Open Positions: 2 across all assets simultaneously.
   - Microstructure Piecewise Ratchet:
     * Phase 0 (BE Lock): At +0.80R gain, move stop to Entry +0.15R (covering 41 bps friction with guaranteed profit).
     * Phase 1 (Profit Lock): At +1.50R gain, move stop to Entry +0.80R.
     * Exit Target: +2.40R to +2.75R.
     * Time Decay: Exit at market if gain < +0.20R within 24 bars (6 hours).

### 3. FORENSIC PROBLEM STATEMENT: RECENT LIVE INCIDENTS & BRANCH WEAKNESSES
During live forward execution on October 6, 2026, our forensic review revealed three critical architectural bottlenecks and execution chain defects that require your exhaustive mathematical restructuring:

#### Incident A: Premature Limit Expiry vs Liquidity Sweep (The TTL Dilemma)
- **Observed Defect:** The autonomous trader correctly identified a textbook Previous Day Low (PDL) Sweep Reclaim on SOL at 119.70 USD, sized the trade with 41 bps friction, and staged limit orders at 120.84, 120.31, and 120.00 USD. However, because the daemon was operating on a rigid 15-minute candle expiry cycle (`expiration_seconds` tightly bound to the current slot), the staged limits expired before institutional market makers had time to sweep the discount liquidity. As a result, the trader sat in 100% cash while the price subsequently rebounded to target.
- **The Core Question:** How do we architect a mathematically rigorous, dynamic Time-To-Live (TTL) and Order Persistence Governor that allows resting limit orders to sit at verified whale walls (e.g. 2 to 6 hours) without polluting the state machine, causing race conditions across 15m candle cycles, or suffering adverse selection when orderbook walls shift?

#### Incident B: Auxiliary Subagent Hallucination vs Ground-Truth Orderbook Math
- **Observed Defect:** When multi-agent cognitive review was triggered on the 14th minute, an auxiliary subagent persona reported "+1.8 standard deviations CVD divergence" and an "empty ask book above 122.00 USD on SOL." Direct forensic querying of the raw JSON feed from `http://localhost:8095/api/live/SOL` proved this was completely fabricated: the true rolling robust Z-score was only +0.92, and there was an 8.04M USD Mega Whale sell wall at 122.34 USD.
- **The Core Question:** How do we mathematically decouple and seal the Cognitive Engine and orderflow scoring pipeline so that LLM/cognitive reasoning NEVER hallucinates statistical values, but instead evaluates strictly deterministic, pre-computed, tamper-proof vector features generated by C++/Polars normalizers?

#### Incident C: Decoupling Pullback (Sleeve S1) from Breakout (Sleeve T1) & Structural Take-Profits
- **Observed Defect:** Pullbacks and breakouts require fundamentally opposing microstructure geometries. In pullbacks, we front-run passive absorption walls (e.g. limit buy at 119.70 ahead of a 4.93M USD whale bid at 119.41 USD). In breakouts, we enter aggressively on momentum when liquidity vacuums appear. Staging a static take-profit (e.g. 123.00 USD) without checking overhead whale walls resulted in targeting an exit beyond an 8.04M USD sell wall at 122.34 USD.
- **The Core Question:** Provide an exhaustive end-to-end mathematical specification for dynamic, orderbook-aware TP placement that snaps take-profits to front-run the first major overhead ask cluster (>2.0M USD), while dynamically adjusting the R-multiple hurdle.

---

### 4. YOUR EXHAUSTIVE DELIVERABLES
Provide an institutional-grade, drop-in engineering audit and complete code implementation for the following:

1. **END-TO-END EXECUTION CHAIN AUDIT:**
   - Forensic trace of the lifecycle: `refresh_background()` -> `manage_active_positions()` -> `refresh_broker_history()` -> `evaluate_market()` -> `_dispatch()`.
   - Identify every potential race condition, stale state risk, or blocking exception in the IPC bridge.

2. **DYNAMIC ORDER PERSISTENCE & TTL GOVERNOR:**
   - Concrete implementation of a persistent limit order manager that supports multi-hour resting limit orders, orderbook tracking, and automatic cancel/replace when resting whale support is pulled.

3. **TAMPER-PROOF DETERMINISTIC FEATURE SCHEMA:**
   - The exact mathematical specification and Python code for deterministic feature extraction (MAD-scaled robust Z-score, orderbook imbalance, aggressor ratio, friction-adjusted fuel ratio) that completely prevents cognitive hallucination.

4. **ORDERBOOK-AWARE STRUCTURAL TAKE-PROFIT & SL RATCHET:**
   - Production code that scans the top 20 L3 orderbook clusters and clamps TP/SL to institutional walls rather than arbitrary fixed R-distances.

Below is the complete, unabridged source code for all active production modules in our system. Analyze them forensically and deliver your comprehensive blueprint and production code.
"""

modules = [
    ("Terminal/OF_Strategy.py", "Terminal/OF_Strategy.py"),
    ("Terminal/Omni_Trader.py", "Terminal/Omni_Trader.py"),
    ("Terminal/Risk_Sizing_Engine.py", "Terminal/Risk_Sizing_Engine.py"),
    ("Terminal/MT5_Execution_Bridge.py", "Terminal/MT5_Execution_Bridge.py"),
    ("Terminal/Cognitive_Engine.py", "Terminal/Cognitive_Engine.py"),
    ("Terminal/Asset_Universe.py", "Terminal/Asset_Universe.py"),
    ("Terminal/Market_Intelligence.py", "Terminal/Market_Intelligence.py"),
]

output_paths = [
    r"C:\Users\SIGMA\Downloads\Ox_Alpha_Omni_Forensic_Chain_Audit.txt",
    r"docs\prompts\Ox_Alpha_Omni_Forensic_Chain_Audit.md"
]

full_prompt = [prompt_header]

for label, path in modules:
    if os.path.exists(path):
        full_prompt.append(f"\n\n{'='*40}\n=== FILE: {label} ===\n{'='*40}\n")
        with open(path, "r", encoding="utf-8") as f:
            full_prompt.append(f.read())
    else:
        print(f"Warning: {path} not found.")

final_text = "".join(full_prompt)

for out_path in output_paths:
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as out:
        out.write(final_text)
    print(f"Written: {out_path} ({len(final_text)} characters, {len(final_text.splitlines())} lines)")
